// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.23.4
// source: proto/codiocmd/codiocmd_service.proto

package codiocmd

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusFileTransfer int32

const (
	StatusFileTransfer_SUCCESS StatusFileTransfer = 0
	StatusFileTransfer_FAIL    StatusFileTransfer = 1
)

// Enum value maps for StatusFileTransfer.
var (
	StatusFileTransfer_name = map[int32]string{
		0: "SUCCESS",
		1: "FAIL",
	}
	StatusFileTransfer_value = map[string]int32{
		"SUCCESS": 0,
		"FAIL":    1,
	}
)

func (x StatusFileTransfer) Enum() *StatusFileTransfer {
	p := new(StatusFileTransfer)
	*p = x
	return p
}

func (x StatusFileTransfer) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusFileTransfer) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_codiocmd_codiocmd_service_proto_enumTypes[0].Descriptor()
}

func (StatusFileTransfer) Type() protoreflect.EnumType {
	return &file_proto_codiocmd_codiocmd_service_proto_enumTypes[0]
}

func (x StatusFileTransfer) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusFileTransfer.Descriptor instead.
func (StatusFileTransfer) EnumDescriptor() ([]byte, []int) {
	return file_proto_codiocmd_codiocmd_service_proto_rawDescGZIP(), []int{0}
}

type WatcherEventTypes_EventType int32

const (
	WatcherEventTypes_CREATE      WatcherEventTypes_EventType = 0
	WatcherEventTypes_WRITE       WatcherEventTypes_EventType = 1
	WatcherEventTypes_REMOVE      WatcherEventTypes_EventType = 2
	WatcherEventTypes_RENAME      WatcherEventTypes_EventType = 3
	WatcherEventTypes_CHMOD       WatcherEventTypes_EventType = 4
	WatcherEventTypes_MOVE        WatcherEventTypes_EventType = 5
	WatcherEventTypes_START_WATCH WatcherEventTypes_EventType = 6
)

// Enum value maps for WatcherEventTypes_EventType.
var (
	WatcherEventTypes_EventType_name = map[int32]string{
		0: "CREATE",
		1: "WRITE",
		2: "REMOVE",
		3: "RENAME",
		4: "CHMOD",
		5: "MOVE",
		6: "START_WATCH",
	}
	WatcherEventTypes_EventType_value = map[string]int32{
		"CREATE":      0,
		"WRITE":       1,
		"REMOVE":      2,
		"RENAME":      3,
		"CHMOD":       4,
		"MOVE":        5,
		"START_WATCH": 6,
	}
)

func (x WatcherEventTypes_EventType) Enum() *WatcherEventTypes_EventType {
	p := new(WatcherEventTypes_EventType)
	*p = x
	return p
}

func (x WatcherEventTypes_EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WatcherEventTypes_EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_codiocmd_codiocmd_service_proto_enumTypes[1].Descriptor()
}

func (WatcherEventTypes_EventType) Type() protoreflect.EnumType {
	return &file_proto_codiocmd_codiocmd_service_proto_enumTypes[1]
}

func (x WatcherEventTypes_EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WatcherEventTypes_EventType.Descriptor instead.
func (WatcherEventTypes_EventType) EnumDescriptor() ([]byte, []int) {
	return file_proto_codiocmd_codiocmd_service_proto_rawDescGZIP(), []int{16, 0}
}

type MetaData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Size          uint32                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	ModTimeNano   int64                  `protobuf:"varint,3,opt,name=mod_time_nano,json=modTimeNano,proto3" json:"mod_time_nano,omitempty"`
	IsSynced      bool                   `protobuf:"varint,4,opt,name=is_synced,json=isSynced,proto3" json:"is_synced,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetaData) Reset() {
	*x = MetaData{}
	mi := &file_proto_codiocmd_codiocmd_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetaData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaData) ProtoMessage() {}

func (x *MetaData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_codiocmd_codiocmd_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaData.ProtoReflect.Descriptor instead.
func (*MetaData) Descriptor() ([]byte, []int) {
	return file_proto_codiocmd_codiocmd_service_proto_rawDescGZIP(), []int{0}
}

func (x *MetaData) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *MetaData) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *MetaData) GetModTimeNano() int64 {
	if x != nil {
		return x.ModTimeNano
	}
	return 0
}

func (x *MetaData) GetIsSynced() bool {
	if x != nil {
		return x.IsSynced
	}
	return false
}

type FileUploadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Request:
	//
	//	*FileUploadRequest_Metadata
	//	*FileUploadRequest_ChunkData
	Request       isFileUploadRequest_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileUploadRequest) Reset() {
	*x = FileUploadRequest{}
	mi := &file_proto_codiocmd_codiocmd_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileUploadRequest) ProtoMessage() {}

func (x *FileUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_codiocmd_codiocmd_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileUploadRequest.ProtoReflect.Descriptor instead.
func (*FileUploadRequest) Descriptor() ([]byte, []int) {
	return file_proto_codiocmd_codiocmd_service_proto_rawDescGZIP(), []int{1}
}

func (x *FileUploadRequest) GetRequest() isFileUploadRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *FileUploadRequest) GetMetadata() *MetaData {
	if x != nil {
		if x, ok := x.Request.(*FileUploadRequest_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *FileUploadRequest) GetChunkData() []byte {
	if x != nil {
		if x, ok := x.Request.(*FileUploadRequest_ChunkData); ok {
			return x.ChunkData
		}
	}
	return nil
}

type isFileUploadRequest_Request interface {
	isFileUploadRequest_Request()
}

type FileUploadRequest_Metadata struct {
	Metadata *MetaData `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type FileUploadRequest_ChunkData struct {
	ChunkData []byte `protobuf:"bytes,2,opt,name=chunk_data,json=chunkData,proto3,oneof"`
}

func (*FileUploadRequest_Metadata) isFileUploadRequest_Request() {}

func (*FileUploadRequest_ChunkData) isFileUploadRequest_Request() {}

type FileUploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        StatusFileTransfer     `protobuf:"varint,1,opt,name=status,proto3,enum=com.codio.chipmunk.proto.codiocmd.StatusFileTransfer" json:"status,omitempty"`
	ErrMsg        string                 `protobuf:"bytes,2,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileUploadResponse) Reset() {
	*x = FileUploadResponse{}
	mi := &file_proto_codiocmd_codiocmd_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileUploadResponse) ProtoMessage() {}

func (x *FileUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_codiocmd_codiocmd_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileUploadResponse.ProtoReflect.Descriptor instead.
func (*FileUploadResponse) Descriptor() ([]byte, []int) {
	return file_proto_codiocmd_codiocmd_service_proto_rawDescGZIP(), []int{2}
}

func (x *FileUploadResponse) GetStatus() StatusFileTransfer {
	if x != nil {
		return x.Status
	}
	return StatusFileTransfer_SUCCESS
}

func (x *FileUploadResponse) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

type FileDownloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileDownloadRequest) Reset() {
	*x = FileDownloadRequest{}
	mi := &file_proto_codiocmd_codiocmd_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileDownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileDownloadRequest) ProtoMessage() {}

func (x *FileDownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_codiocmd_codiocmd_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileDownloadRequest.ProtoReflect.Descriptor instead.
func (*FileDownloadRequest) Descriptor() ([]byte, []int) {
	return file_proto_codiocmd_codiocmd_service_proto_rawDescGZIP(), []int{3}
}

func (x *FileDownloadRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type FileDownloadResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Request:
	//
	//	*FileDownloadResponse_Metadata
	//	*FileDownloadResponse_ChunkData
	Request       isFileDownloadResponse_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileDownloadResponse) Reset() {
	*x = FileDownloadResponse{}
	mi := &file_proto_codiocmd_codiocmd_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileDownloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileDownloadResponse) ProtoMessage() {}

func (x *FileDownloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_codiocmd_codiocmd_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileDownloadResponse.ProtoReflect.Descriptor instead.
func (*FileDownloadResponse) Descriptor() ([]byte, []int) {
	return file_proto_codiocmd_codiocmd_service_proto_rawDescGZIP(), []int{4}
}

func (x *FileDownloadResponse) GetRequest() isFileDownloadResponse_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *FileDownloadResponse) GetMetadata() *MetaData {
	if x != nil {
		if x, ok := x.Request.(*FileDownloadResponse_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *FileDownloadResponse) GetChunkData() []byte {
	if x != nil {
		if x, ok := x.Request.(*FileDownloadResponse_ChunkData); ok {
			return x.ChunkData
		}
	}
	return nil
}

type isFileDownloadResponse_Request interface {
	isFileDownloadResponse_Request()
}

type FileDownloadResponse_Metadata struct {
	Metadata *MetaData `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type FileDownloadResponse_ChunkData struct {
	ChunkData []byte `protobuf:"bytes,2,opt,name=chunk_data,json=chunkData,proto3,oneof"`
}

func (*FileDownloadResponse_Metadata) isFileDownloadResponse_Request() {}

func (*FileDownloadResponse_ChunkData) isFileDownloadResponse_Request() {}

type ExecRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cmd           string                 `protobuf:"bytes,1,opt,name=cmd,proto3" json:"cmd,omitempty"`
	Args          []string               `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecRequest) Reset() {
	*x = ExecRequest{}
	mi := &file_proto_codiocmd_codiocmd_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecRequest) ProtoMessage() {}

func (x *ExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_codiocmd_codiocmd_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecRequest.ProtoReflect.Descriptor instead.
func (*ExecRequest) Descriptor() ([]byte, []int) {
	return file_proto_codiocmd_codiocmd_service_proto_rawDescGZIP(), []int{5}
}

func (x *ExecRequest) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

func (x *ExecRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

type ExecResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Out           string                 `protobuf:"bytes,2,opt,name=out,proto3" json:"out,omitempty"`
	Err           string                 `protobuf:"bytes,3,opt,name=err,proto3" json:"err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecResponse) Reset() {
	*x = ExecResponse{}
	mi := &file_proto_codiocmd_codiocmd_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecResponse) ProtoMessage() {}

func (x *ExecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_codiocmd_codiocmd_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecResponse.ProtoReflect.Descriptor instead.
func (*ExecResponse) Descriptor() ([]byte, []int) {
	return file_proto_codiocmd_codiocmd_service_proto_rawDescGZIP(), []int{6}
}

func (x *ExecResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ExecResponse) GetOut() string {
	if x != nil {
		return x.Out
	}
	return ""
}

func (x *ExecResponse) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

type ExecAsyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cmd           string                 `protobuf:"bytes,1,opt,name=cmd,proto3" json:"cmd,omitempty"`
	Args          []string               `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecAsyncRequest) Reset() {
	*x = ExecAsyncRequest{}
	mi := &file_proto_codiocmd_codiocmd_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecAsyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecAsyncRequest) ProtoMessage() {}

func (x *ExecAsyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_codiocmd_codiocmd_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecAsyncRequest.ProtoReflect.Descriptor instead.
func (*ExecAsyncRequest) Descriptor() ([]byte, []int) {
	return file_proto_codiocmd_codiocmd_service_proto_rawDescGZIP(), []int{7}
}

func (x *ExecAsyncRequest) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

func (x *ExecAsyncRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

type ExecAsyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	ErrMsg        string                 `protobuf:"bytes,2,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecAsyncResponse) Reset() {
	*x = ExecAsyncResponse{}
	mi := &file_proto_codiocmd_codiocmd_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecAsyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecAsyncResponse) ProtoMessage() {}

func (x *ExecAsyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_codiocmd_codiocmd_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecAsyncResponse.ProtoReflect.Descriptor instead.
func (*ExecAsyncResponse) Descriptor() ([]byte, []int) {
	return file_proto_codiocmd_codiocmd_service_proto_rawDescGZIP(), []int{8}
}

func (x *ExecAsyncResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ExecAsyncResponse) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_proto_codiocmd_codiocmd_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_codiocmd_codiocmd_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_proto_codiocmd_codiocmd_service_proto_rawDescGZIP(), []int{9}
}

func (x *PingRequest) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_proto_codiocmd_codiocmd_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_codiocmd_codiocmd_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_proto_codiocmd_codiocmd_service_proto_rawDescGZIP(), []int{10}
}

func (x *PingResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type GetVMHostNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVMHostNameRequest) Reset() {
	*x = GetVMHostNameRequest{}
	mi := &file_proto_codiocmd_codiocmd_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVMHostNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVMHostNameRequest) ProtoMessage() {}

func (x *GetVMHostNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_codiocmd_codiocmd_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVMHostNameRequest.ProtoReflect.Descriptor instead.
func (*GetVMHostNameRequest) Descriptor() ([]byte, []int) {
	return file_proto_codiocmd_codiocmd_service_proto_rawDescGZIP(), []int{11}
}

type GetVMHostNameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostName      string                 `protobuf:"bytes,1,opt,name=host_name,json=hostName,proto3" json:"host_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVMHostNameResponse) Reset() {
	*x = GetVMHostNameResponse{}
	mi := &file_proto_codiocmd_codiocmd_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVMHostNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVMHostNameResponse) ProtoMessage() {}

func (x *GetVMHostNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_codiocmd_codiocmd_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVMHostNameResponse.ProtoReflect.Descriptor instead.
func (*GetVMHostNameResponse) Descriptor() ([]byte, []int) {
	return file_proto_codiocmd_codiocmd_service_proto_rawDescGZIP(), []int{12}
}

func (x *GetVMHostNameResponse) GetHostName() string {
	if x != nil {
		return x.HostName
	}
	return ""
}

type GetRemoteFileListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRemoteFileListRequest) Reset() {
	*x = GetRemoteFileListRequest{}
	mi := &file_proto_codiocmd_codiocmd_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRemoteFileListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRemoteFileListRequest) ProtoMessage() {}

func (x *GetRemoteFileListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_codiocmd_codiocmd_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRemoteFileListRequest.ProtoReflect.Descriptor instead.
func (*GetRemoteFileListRequest) Descriptor() ([]byte, []int) {
	return file_proto_codiocmd_codiocmd_service_proto_rawDescGZIP(), []int{13}
}

func (x *GetRemoteFileListRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type GetRemoteFileListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	ModTimeNano   int64                  `protobuf:"varint,2,opt,name=mod_time_nano,json=modTimeNano,proto3" json:"mod_time_nano,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRemoteFileListResponse) Reset() {
	*x = GetRemoteFileListResponse{}
	mi := &file_proto_codiocmd_codiocmd_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRemoteFileListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRemoteFileListResponse) ProtoMessage() {}

func (x *GetRemoteFileListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_codiocmd_codiocmd_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRemoteFileListResponse.ProtoReflect.Descriptor instead.
func (*GetRemoteFileListResponse) Descriptor() ([]byte, []int) {
	return file_proto_codiocmd_codiocmd_service_proto_rawDescGZIP(), []int{14}
}

func (x *GetRemoteFileListResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *GetRemoteFileListResponse) GetModTimeNano() int64 {
	if x != nil {
		return x.ModTimeNano
	}
	return 0
}

type FileWatcherEvent struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	EventType     WatcherEventTypes_EventType `protobuf:"varint,1,opt,name=event_type,json=eventType,proto3,enum=com.codio.chipmunk.proto.codiocmd.WatcherEventTypes_EventType" json:"event_type,omitempty"`
	Path          string                      `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	OldPath       string                      `protobuf:"bytes,3,opt,name=old_path,json=oldPath,proto3" json:"old_path,omitempty"`
	IsDir         bool                        `protobuf:"varint,4,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	ModTimeNano   int64                       `protobuf:"varint,5,opt,name=mod_time_nano,json=modTimeNano,proto3" json:"mod_time_nano,omitempty"`
	FileMode      uint32                      `protobuf:"varint,6,opt,name=file_mode,json=fileMode,proto3" json:"file_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileWatcherEvent) Reset() {
	*x = FileWatcherEvent{}
	mi := &file_proto_codiocmd_codiocmd_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileWatcherEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileWatcherEvent) ProtoMessage() {}

func (x *FileWatcherEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_codiocmd_codiocmd_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileWatcherEvent.ProtoReflect.Descriptor instead.
func (*FileWatcherEvent) Descriptor() ([]byte, []int) {
	return file_proto_codiocmd_codiocmd_service_proto_rawDescGZIP(), []int{15}
}

func (x *FileWatcherEvent) GetEventType() WatcherEventTypes_EventType {
	if x != nil {
		return x.EventType
	}
	return WatcherEventTypes_CREATE
}

func (x *FileWatcherEvent) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileWatcherEvent) GetOldPath() string {
	if x != nil {
		return x.OldPath
	}
	return ""
}

func (x *FileWatcherEvent) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *FileWatcherEvent) GetModTimeNano() int64 {
	if x != nil {
		return x.ModTimeNano
	}
	return 0
}

func (x *FileWatcherEvent) GetFileMode() uint32 {
	if x != nil {
		return x.FileMode
	}
	return 0
}

type WatcherEventTypes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatcherEventTypes) Reset() {
	*x = WatcherEventTypes{}
	mi := &file_proto_codiocmd_codiocmd_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatcherEventTypes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatcherEventTypes) ProtoMessage() {}

func (x *WatcherEventTypes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_codiocmd_codiocmd_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatcherEventTypes.ProtoReflect.Descriptor instead.
func (*WatcherEventTypes) Descriptor() ([]byte, []int) {
	return file_proto_codiocmd_codiocmd_service_proto_rawDescGZIP(), []int{16}
}

type GetReusableTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReusableTokenRequest) Reset() {
	*x = GetReusableTokenRequest{}
	mi := &file_proto_codiocmd_codiocmd_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReusableTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReusableTokenRequest) ProtoMessage() {}

func (x *GetReusableTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_codiocmd_codiocmd_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReusableTokenRequest.ProtoReflect.Descriptor instead.
func (*GetReusableTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_codiocmd_codiocmd_service_proto_rawDescGZIP(), []int{17}
}

type GetReusableTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReusableTokenResponse) Reset() {
	*x = GetReusableTokenResponse{}
	mi := &file_proto_codiocmd_codiocmd_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReusableTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReusableTokenResponse) ProtoMessage() {}

func (x *GetReusableTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_codiocmd_codiocmd_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReusableTokenResponse.ProtoReflect.Descriptor instead.
func (*GetReusableTokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_codiocmd_codiocmd_service_proto_rawDescGZIP(), []int{18}
}

func (x *GetReusableTokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_proto_codiocmd_codiocmd_service_proto protoreflect.FileDescriptor

const file_proto_codiocmd_codiocmd_service_proto_rawDesc = "" +
	"\n" +
	"%proto/codiocmd/codiocmd_service.proto\x12!com.codio.chipmunk.proto.codiocmd\"s\n" +
	"\bMetaData\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04size\x18\x02 \x01(\rR\x04size\x12\"\n" +
	"\rmod_time_nano\x18\x03 \x01(\x03R\vmodTimeNano\x12\x1b\n" +
	"\tis_synced\x18\x04 \x01(\bR\bisSynced\"\x8a\x01\n" +
	"\x11FileUploadRequest\x12I\n" +
	"\bmetadata\x18\x01 \x01(\v2+.com.codio.chipmunk.proto.codiocmd.MetaDataH\x00R\bmetadata\x12\x1f\n" +
	"\n" +
	"chunk_data\x18\x02 \x01(\fH\x00R\tchunkDataB\t\n" +
	"\arequest\"|\n" +
	"\x12FileUploadResponse\x12M\n" +
	"\x06status\x18\x01 \x01(\x0e25.com.codio.chipmunk.proto.codiocmd.StatusFileTransferR\x06status\x12\x17\n" +
	"\aerr_msg\x18\x02 \x01(\tR\x06errMsg\")\n" +
	"\x13FileDownloadRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"\x8d\x01\n" +
	"\x14FileDownloadResponse\x12I\n" +
	"\bmetadata\x18\x01 \x01(\v2+.com.codio.chipmunk.proto.codiocmd.MetaDataH\x00R\bmetadata\x12\x1f\n" +
	"\n" +
	"chunk_data\x18\x02 \x01(\fH\x00R\tchunkDataB\t\n" +
	"\arequest\"3\n" +
	"\vExecRequest\x12\x10\n" +
	"\x03cmd\x18\x01 \x01(\tR\x03cmd\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\"B\n" +
	"\fExecResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x10\n" +
	"\x03out\x18\x02 \x01(\tR\x03out\x12\x10\n" +
	"\x03err\x18\x03 \x01(\tR\x03err\"8\n" +
	"\x10ExecAsyncRequest\x12\x10\n" +
	"\x03cmd\x18\x01 \x01(\tR\x03cmd\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\"<\n" +
	"\x11ExecAsyncResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x17\n" +
	"\aerr_msg\x18\x02 \x01(\tR\x06errMsg\"\x1f\n" +
	"\vPingRequest\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\" \n" +
	"\fPingResponse\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\"\x16\n" +
	"\x14GetVMHostNameRequest\"4\n" +
	"\x15GetVMHostNameResponse\x12\x1b\n" +
	"\thost_name\x18\x01 \x01(\tR\bhostName\".\n" +
	"\x18GetRemoteFileListRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"S\n" +
	"\x19GetRemoteFileListResponse\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\"\n" +
	"\rmod_time_nano\x18\x02 \x01(\x03R\vmodTimeNano\"\xf8\x01\n" +
	"\x10FileWatcherEvent\x12]\n" +
	"\n" +
	"event_type\x18\x01 \x01(\x0e2>.com.codio.chipmunk.proto.codiocmd.WatcherEventTypes.EventTypeR\teventType\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x19\n" +
	"\bold_path\x18\x03 \x01(\tR\aoldPath\x12\x15\n" +
	"\x06is_dir\x18\x04 \x01(\bR\x05isDir\x12\"\n" +
	"\rmod_time_nano\x18\x05 \x01(\x03R\vmodTimeNano\x12\x1b\n" +
	"\tfile_mode\x18\x06 \x01(\rR\bfileMode\"u\n" +
	"\x11WatcherEventTypes\"`\n" +
	"\tEventType\x12\n" +
	"\n" +
	"\x06CREATE\x10\x00\x12\t\n" +
	"\x05WRITE\x10\x01\x12\n" +
	"\n" +
	"\x06REMOVE\x10\x02\x12\n" +
	"\n" +
	"\x06RENAME\x10\x03\x12\t\n" +
	"\x05CHMOD\x10\x04\x12\b\n" +
	"\x04MOVE\x10\x05\x12\x0f\n" +
	"\vSTART_WATCH\x10\x06\"\x19\n" +
	"\x17GetReusableTokenRequest\"0\n" +
	"\x18GetReusableTokenResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token*+\n" +
	"\x12StatusFileTransfer\x12\v\n" +
	"\aSUCCESS\x10\x00\x12\b\n" +
	"\x04FAIL\x10\x012\xf5\b\n" +
	"\bCodioCmd\x12{\n" +
	"\n" +
	"FileUpload\x124.com.codio.chipmunk.proto.codiocmd.FileUploadRequest\x1a5.com.codio.chipmunk.proto.codiocmd.FileUploadResponse(\x01\x12\x81\x01\n" +
	"\fFileDownload\x126.com.codio.chipmunk.proto.codiocmd.FileDownloadRequest\x1a7.com.codio.chipmunk.proto.codiocmd.FileDownloadResponse0\x01\x12g\n" +
	"\x04Exec\x12..com.codio.chipmunk.proto.codiocmd.ExecRequest\x1a/.com.codio.chipmunk.proto.codiocmd.ExecResponse\x12v\n" +
	"\tExecAsync\x123.com.codio.chipmunk.proto.codiocmd.ExecAsyncRequest\x1a4.com.codio.chipmunk.proto.codiocmd.ExecAsyncResponse\x12g\n" +
	"\x04Ping\x12..com.codio.chipmunk.proto.codiocmd.PingRequest\x1a/.com.codio.chipmunk.proto.codiocmd.PingResponse\x12\x82\x01\n" +
	"\rGetVMHostName\x127.com.codio.chipmunk.proto.codiocmd.GetVMHostNameRequest\x1a8.com.codio.chipmunk.proto.codiocmd.GetVMHostNameResponse\x12\x90\x01\n" +
	"\x11GetRemoteFileList\x12;.com.codio.chipmunk.proto.codiocmd.GetRemoteFileListRequest\x1a<.com.codio.chipmunk.proto.codiocmd.GetRemoteFileListResponse0\x01\x12x\n" +
	"\bSyncPath\x123.com.codio.chipmunk.proto.codiocmd.FileWatcherEvent\x1a3.com.codio.chipmunk.proto.codiocmd.FileWatcherEvent(\x010\x01\x12\x8b\x01\n" +
	"\x10GetReusableToken\x12:.com.codio.chipmunk.proto.codiocmd.GetReusableTokenRequest\x1a;.com.codio.chipmunk.proto.codiocmd.GetReusableTokenResponseB8Z6github.com/codio/chipmunk-interface-gen/proto/codiocmdb\x06proto3"

var (
	file_proto_codiocmd_codiocmd_service_proto_rawDescOnce sync.Once
	file_proto_codiocmd_codiocmd_service_proto_rawDescData []byte
)

func file_proto_codiocmd_codiocmd_service_proto_rawDescGZIP() []byte {
	file_proto_codiocmd_codiocmd_service_proto_rawDescOnce.Do(func() {
		file_proto_codiocmd_codiocmd_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_codiocmd_codiocmd_service_proto_rawDesc), len(file_proto_codiocmd_codiocmd_service_proto_rawDesc)))
	})
	return file_proto_codiocmd_codiocmd_service_proto_rawDescData
}

var file_proto_codiocmd_codiocmd_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_codiocmd_codiocmd_service_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_proto_codiocmd_codiocmd_service_proto_goTypes = []any{
	(StatusFileTransfer)(0),           // 0: com.codio.chipmunk.proto.codiocmd.StatusFileTransfer
	(WatcherEventTypes_EventType)(0),  // 1: com.codio.chipmunk.proto.codiocmd.WatcherEventTypes.EventType
	(*MetaData)(nil),                  // 2: com.codio.chipmunk.proto.codiocmd.MetaData
	(*FileUploadRequest)(nil),         // 3: com.codio.chipmunk.proto.codiocmd.FileUploadRequest
	(*FileUploadResponse)(nil),        // 4: com.codio.chipmunk.proto.codiocmd.FileUploadResponse
	(*FileDownloadRequest)(nil),       // 5: com.codio.chipmunk.proto.codiocmd.FileDownloadRequest
	(*FileDownloadResponse)(nil),      // 6: com.codio.chipmunk.proto.codiocmd.FileDownloadResponse
	(*ExecRequest)(nil),               // 7: com.codio.chipmunk.proto.codiocmd.ExecRequest
	(*ExecResponse)(nil),              // 8: com.codio.chipmunk.proto.codiocmd.ExecResponse
	(*ExecAsyncRequest)(nil),          // 9: com.codio.chipmunk.proto.codiocmd.ExecAsyncRequest
	(*ExecAsyncResponse)(nil),         // 10: com.codio.chipmunk.proto.codiocmd.ExecAsyncResponse
	(*PingRequest)(nil),               // 11: com.codio.chipmunk.proto.codiocmd.PingRequest
	(*PingResponse)(nil),              // 12: com.codio.chipmunk.proto.codiocmd.PingResponse
	(*GetVMHostNameRequest)(nil),      // 13: com.codio.chipmunk.proto.codiocmd.GetVMHostNameRequest
	(*GetVMHostNameResponse)(nil),     // 14: com.codio.chipmunk.proto.codiocmd.GetVMHostNameResponse
	(*GetRemoteFileListRequest)(nil),  // 15: com.codio.chipmunk.proto.codiocmd.GetRemoteFileListRequest
	(*GetRemoteFileListResponse)(nil), // 16: com.codio.chipmunk.proto.codiocmd.GetRemoteFileListResponse
	(*FileWatcherEvent)(nil),          // 17: com.codio.chipmunk.proto.codiocmd.FileWatcherEvent
	(*WatcherEventTypes)(nil),         // 18: com.codio.chipmunk.proto.codiocmd.WatcherEventTypes
	(*GetReusableTokenRequest)(nil),   // 19: com.codio.chipmunk.proto.codiocmd.GetReusableTokenRequest
	(*GetReusableTokenResponse)(nil),  // 20: com.codio.chipmunk.proto.codiocmd.GetReusableTokenResponse
}
var file_proto_codiocmd_codiocmd_service_proto_depIdxs = []int32{
	2,  // 0: com.codio.chipmunk.proto.codiocmd.FileUploadRequest.metadata:type_name -> com.codio.chipmunk.proto.codiocmd.MetaData
	0,  // 1: com.codio.chipmunk.proto.codiocmd.FileUploadResponse.status:type_name -> com.codio.chipmunk.proto.codiocmd.StatusFileTransfer
	2,  // 2: com.codio.chipmunk.proto.codiocmd.FileDownloadResponse.metadata:type_name -> com.codio.chipmunk.proto.codiocmd.MetaData
	1,  // 3: com.codio.chipmunk.proto.codiocmd.FileWatcherEvent.event_type:type_name -> com.codio.chipmunk.proto.codiocmd.WatcherEventTypes.EventType
	3,  // 4: com.codio.chipmunk.proto.codiocmd.CodioCmd.FileUpload:input_type -> com.codio.chipmunk.proto.codiocmd.FileUploadRequest
	5,  // 5: com.codio.chipmunk.proto.codiocmd.CodioCmd.FileDownload:input_type -> com.codio.chipmunk.proto.codiocmd.FileDownloadRequest
	7,  // 6: com.codio.chipmunk.proto.codiocmd.CodioCmd.Exec:input_type -> com.codio.chipmunk.proto.codiocmd.ExecRequest
	9,  // 7: com.codio.chipmunk.proto.codiocmd.CodioCmd.ExecAsync:input_type -> com.codio.chipmunk.proto.codiocmd.ExecAsyncRequest
	11, // 8: com.codio.chipmunk.proto.codiocmd.CodioCmd.Ping:input_type -> com.codio.chipmunk.proto.codiocmd.PingRequest
	13, // 9: com.codio.chipmunk.proto.codiocmd.CodioCmd.GetVMHostName:input_type -> com.codio.chipmunk.proto.codiocmd.GetVMHostNameRequest
	15, // 10: com.codio.chipmunk.proto.codiocmd.CodioCmd.GetRemoteFileList:input_type -> com.codio.chipmunk.proto.codiocmd.GetRemoteFileListRequest
	17, // 11: com.codio.chipmunk.proto.codiocmd.CodioCmd.SyncPath:input_type -> com.codio.chipmunk.proto.codiocmd.FileWatcherEvent
	19, // 12: com.codio.chipmunk.proto.codiocmd.CodioCmd.GetReusableToken:input_type -> com.codio.chipmunk.proto.codiocmd.GetReusableTokenRequest
	4,  // 13: com.codio.chipmunk.proto.codiocmd.CodioCmd.FileUpload:output_type -> com.codio.chipmunk.proto.codiocmd.FileUploadResponse
	6,  // 14: com.codio.chipmunk.proto.codiocmd.CodioCmd.FileDownload:output_type -> com.codio.chipmunk.proto.codiocmd.FileDownloadResponse
	8,  // 15: com.codio.chipmunk.proto.codiocmd.CodioCmd.Exec:output_type -> com.codio.chipmunk.proto.codiocmd.ExecResponse
	10, // 16: com.codio.chipmunk.proto.codiocmd.CodioCmd.ExecAsync:output_type -> com.codio.chipmunk.proto.codiocmd.ExecAsyncResponse
	12, // 17: com.codio.chipmunk.proto.codiocmd.CodioCmd.Ping:output_type -> com.codio.chipmunk.proto.codiocmd.PingResponse
	14, // 18: com.codio.chipmunk.proto.codiocmd.CodioCmd.GetVMHostName:output_type -> com.codio.chipmunk.proto.codiocmd.GetVMHostNameResponse
	16, // 19: com.codio.chipmunk.proto.codiocmd.CodioCmd.GetRemoteFileList:output_type -> com.codio.chipmunk.proto.codiocmd.GetRemoteFileListResponse
	17, // 20: com.codio.chipmunk.proto.codiocmd.CodioCmd.SyncPath:output_type -> com.codio.chipmunk.proto.codiocmd.FileWatcherEvent
	20, // 21: com.codio.chipmunk.proto.codiocmd.CodioCmd.GetReusableToken:output_type -> com.codio.chipmunk.proto.codiocmd.GetReusableTokenResponse
	13, // [13:22] is the sub-list for method output_type
	4,  // [4:13] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_codiocmd_codiocmd_service_proto_init() }
func file_proto_codiocmd_codiocmd_service_proto_init() {
	if File_proto_codiocmd_codiocmd_service_proto != nil {
		return
	}
	file_proto_codiocmd_codiocmd_service_proto_msgTypes[1].OneofWrappers = []any{
		(*FileUploadRequest_Metadata)(nil),
		(*FileUploadRequest_ChunkData)(nil),
	}
	file_proto_codiocmd_codiocmd_service_proto_msgTypes[4].OneofWrappers = []any{
		(*FileDownloadResponse_Metadata)(nil),
		(*FileDownloadResponse_ChunkData)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_codiocmd_codiocmd_service_proto_rawDesc), len(file_proto_codiocmd_codiocmd_service_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_codiocmd_codiocmd_service_proto_goTypes,
		DependencyIndexes: file_proto_codiocmd_codiocmd_service_proto_depIdxs,
		EnumInfos:         file_proto_codiocmd_codiocmd_service_proto_enumTypes,
		MessageInfos:      file_proto_codiocmd_codiocmd_service_proto_msgTypes,
	}.Build()
	File_proto_codiocmd_codiocmd_service_proto = out.File
	file_proto_codiocmd_codiocmd_service_proto_goTypes = nil
	file_proto_codiocmd_codiocmd_service_proto_depIdxs = nil
}
