// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.23.4
// source: proto/codiovmrange/codiovmrange_service.proto

package codiovmrange

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VmStatus int32

const (
	VmStatus_STOPPED VmStatus = 0
	VmStatus_RUNNING VmStatus = 1
)

// Enum value maps for VmStatus.
var (
	VmStatus_name = map[int32]string{
		0: "STOPPED",
		1: "RUNNING",
	}
	VmStatus_value = map[string]int32{
		"STOPPED": 0,
		"RUNNING": 1,
	}
)

func (x VmStatus) Enum() *VmStatus {
	p := new(VmStatus)
	*p = x
	return p
}

func (x VmStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VmStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_codiovmrange_codiovmrange_service_proto_enumTypes[0].Descriptor()
}

func (VmStatus) Type() protoreflect.EnumType {
	return &file_proto_codiovmrange_codiovmrange_service_proto_enumTypes[0]
}

func (x VmStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VmStatus.Descriptor instead.
func (VmStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_codiovmrange_codiovmrange_service_proto_rawDescGZIP(), []int{0}
}

type VmParameters_MemoryUnit int32

const (
	VmParameters_KiB VmParameters_MemoryUnit = 0
	VmParameters_MiB VmParameters_MemoryUnit = 1
	VmParameters_GiB VmParameters_MemoryUnit = 2
)

// Enum value maps for VmParameters_MemoryUnit.
var (
	VmParameters_MemoryUnit_name = map[int32]string{
		0: "KiB",
		1: "MiB",
		2: "GiB",
	}
	VmParameters_MemoryUnit_value = map[string]int32{
		"KiB": 0,
		"MiB": 1,
		"GiB": 2,
	}
)

func (x VmParameters_MemoryUnit) Enum() *VmParameters_MemoryUnit {
	p := new(VmParameters_MemoryUnit)
	*p = x
	return p
}

func (x VmParameters_MemoryUnit) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VmParameters_MemoryUnit) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_codiovmrange_codiovmrange_service_proto_enumTypes[1].Descriptor()
}

func (VmParameters_MemoryUnit) Type() protoreflect.EnumType {
	return &file_proto_codiovmrange_codiovmrange_service_proto_enumTypes[1]
}

func (x VmParameters_MemoryUnit) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VmParameters_MemoryUnit.Descriptor instead.
func (VmParameters_MemoryUnit) EnumDescriptor() ([]byte, []int) {
	return file_proto_codiovmrange_codiovmrange_service_proto_rawDescGZIP(), []int{11, 0}
}

type CreateVmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageName     string                 `protobuf:"bytes,1,opt,name=image_name,json=imageName,proto3" json:"image_name,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,2,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	DomainXml     string                 `protobuf:"bytes,3,opt,name=domain_xml,json=domainXml,proto3" json:"domain_xml,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVmRequest) Reset() {
	*x = CreateVmRequest{}
	mi := &file_proto_codiovmrange_codiovmrange_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVmRequest) ProtoMessage() {}

func (x *CreateVmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_codiovmrange_codiovmrange_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVmRequest.ProtoReflect.Descriptor instead.
func (*CreateVmRequest) Descriptor() ([]byte, []int) {
	return file_proto_codiovmrange_codiovmrange_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateVmRequest) GetImageName() string {
	if x != nil {
		return x.ImageName
	}
	return ""
}

func (x *CreateVmRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *CreateVmRequest) GetDomainXml() string {
	if x != nil {
		return x.DomainXml
	}
	return ""
}

type CreateVmResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Status:
	//
	//	*CreateVmResponse_Error
	//	*CreateVmResponse_Completed
	//	*CreateVmResponse_Progress
	Status        isCreateVmResponse_Status `protobuf_oneof:"status"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVmResponse) Reset() {
	*x = CreateVmResponse{}
	mi := &file_proto_codiovmrange_codiovmrange_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVmResponse) ProtoMessage() {}

func (x *CreateVmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_codiovmrange_codiovmrange_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVmResponse.ProtoReflect.Descriptor instead.
func (*CreateVmResponse) Descriptor() ([]byte, []int) {
	return file_proto_codiovmrange_codiovmrange_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateVmResponse) GetStatus() isCreateVmResponse_Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *CreateVmResponse) GetError() *CreateVmResponse_CreateVmError {
	if x != nil {
		if x, ok := x.Status.(*CreateVmResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *CreateVmResponse) GetCompleted() *CreateVmResponse_CreateVmCompleted {
	if x != nil {
		if x, ok := x.Status.(*CreateVmResponse_Completed); ok {
			return x.Completed
		}
	}
	return nil
}

func (x *CreateVmResponse) GetProgress() *CreateVmResponse_CreateVmProgress {
	if x != nil {
		if x, ok := x.Status.(*CreateVmResponse_Progress); ok {
			return x.Progress
		}
	}
	return nil
}

type isCreateVmResponse_Status interface {
	isCreateVmResponse_Status()
}

type CreateVmResponse_Error struct {
	Error *CreateVmResponse_CreateVmError `protobuf:"bytes,1,opt,name=error,proto3,oneof"`
}

type CreateVmResponse_Completed struct {
	Completed *CreateVmResponse_CreateVmCompleted `protobuf:"bytes,2,opt,name=completed,proto3,oneof"`
}

type CreateVmResponse_Progress struct {
	Progress *CreateVmResponse_CreateVmProgress `protobuf:"bytes,3,opt,name=progress,proto3,oneof"`
}

func (*CreateVmResponse_Error) isCreateVmResponse_Status() {}

func (*CreateVmResponse_Completed) isCreateVmResponse_Status() {}

func (*CreateVmResponse_Progress) isCreateVmResponse_Status() {}

type ListVmsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVmsRequest) Reset() {
	*x = ListVmsRequest{}
	mi := &file_proto_codiovmrange_codiovmrange_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVmsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVmsRequest) ProtoMessage() {}

func (x *ListVmsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_codiovmrange_codiovmrange_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVmsRequest.ProtoReflect.Descriptor instead.
func (*ListVmsRequest) Descriptor() ([]byte, []int) {
	return file_proto_codiovmrange_codiovmrange_service_proto_rawDescGZIP(), []int{2}
}

type Vm struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status        VmStatus               `protobuf:"varint,3,opt,name=status,proto3,enum=com.codio.chipmunk.proto.codiovmrange.VmStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vm) Reset() {
	*x = Vm{}
	mi := &file_proto_codiovmrange_codiovmrange_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vm) ProtoMessage() {}

func (x *Vm) ProtoReflect() protoreflect.Message {
	mi := &file_proto_codiovmrange_codiovmrange_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vm.ProtoReflect.Descriptor instead.
func (*Vm) Descriptor() ([]byte, []int) {
	return file_proto_codiovmrange_codiovmrange_service_proto_rawDescGZIP(), []int{3}
}

func (x *Vm) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Vm) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Vm) GetStatus() VmStatus {
	if x != nil {
		return x.Status
	}
	return VmStatus_STOPPED
}

type ListVmsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vms           []*Vm                  `protobuf:"bytes,1,rep,name=vms,proto3" json:"vms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVmsResponse) Reset() {
	*x = ListVmsResponse{}
	mi := &file_proto_codiovmrange_codiovmrange_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVmsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVmsResponse) ProtoMessage() {}

func (x *ListVmsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_codiovmrange_codiovmrange_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVmsResponse.ProtoReflect.Descriptor instead.
func (*ListVmsResponse) Descriptor() ([]byte, []int) {
	return file_proto_codiovmrange_codiovmrange_service_proto_rawDescGZIP(), []int{4}
}

func (x *ListVmsResponse) GetVms() []*Vm {
	if x != nil {
		return x.Vms
	}
	return nil
}

type StartVmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartVmRequest) Reset() {
	*x = StartVmRequest{}
	mi := &file_proto_codiovmrange_codiovmrange_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartVmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartVmRequest) ProtoMessage() {}

func (x *StartVmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_codiovmrange_codiovmrange_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartVmRequest.ProtoReflect.Descriptor instead.
func (*StartVmRequest) Descriptor() ([]byte, []int) {
	return file_proto_codiovmrange_codiovmrange_service_proto_rawDescGZIP(), []int{5}
}

func (x *StartVmRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type StartVmResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartVmResponse) Reset() {
	*x = StartVmResponse{}
	mi := &file_proto_codiovmrange_codiovmrange_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartVmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartVmResponse) ProtoMessage() {}

func (x *StartVmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_codiovmrange_codiovmrange_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartVmResponse.ProtoReflect.Descriptor instead.
func (*StartVmResponse) Descriptor() ([]byte, []int) {
	return file_proto_codiovmrange_codiovmrange_service_proto_rawDescGZIP(), []int{6}
}

type StopVmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopVmRequest) Reset() {
	*x = StopVmRequest{}
	mi := &file_proto_codiovmrange_codiovmrange_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopVmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopVmRequest) ProtoMessage() {}

func (x *StopVmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_codiovmrange_codiovmrange_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopVmRequest.ProtoReflect.Descriptor instead.
func (*StopVmRequest) Descriptor() ([]byte, []int) {
	return file_proto_codiovmrange_codiovmrange_service_proto_rawDescGZIP(), []int{7}
}

func (x *StopVmRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type StopVmResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopVmResponse) Reset() {
	*x = StopVmResponse{}
	mi := &file_proto_codiovmrange_codiovmrange_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopVmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopVmResponse) ProtoMessage() {}

func (x *StopVmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_codiovmrange_codiovmrange_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopVmResponse.ProtoReflect.Descriptor instead.
func (*StopVmResponse) Descriptor() ([]byte, []int) {
	return file_proto_codiovmrange_codiovmrange_service_proto_rawDescGZIP(), []int{8}
}

type DestroyVmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyVmRequest) Reset() {
	*x = DestroyVmRequest{}
	mi := &file_proto_codiovmrange_codiovmrange_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyVmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyVmRequest) ProtoMessage() {}

func (x *DestroyVmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_codiovmrange_codiovmrange_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyVmRequest.ProtoReflect.Descriptor instead.
func (*DestroyVmRequest) Descriptor() ([]byte, []int) {
	return file_proto_codiovmrange_codiovmrange_service_proto_rawDescGZIP(), []int{9}
}

func (x *DestroyVmRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DestroyVmResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyVmResponse) Reset() {
	*x = DestroyVmResponse{}
	mi := &file_proto_codiovmrange_codiovmrange_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyVmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyVmResponse) ProtoMessage() {}

func (x *DestroyVmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_codiovmrange_codiovmrange_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyVmResponse.ProtoReflect.Descriptor instead.
func (*DestroyVmResponse) Descriptor() ([]byte, []int) {
	return file_proto_codiovmrange_codiovmrange_service_proto_rawDescGZIP(), []int{10}
}

type VmParameters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cpus          *wrapperspb.Int32Value `protobuf:"bytes,1,opt,name=cpus,proto3" json:"cpus,omitempty"`
	Memory        *VmParameters_Memory   `protobuf:"bytes,2,opt,name=memory,proto3" json:"memory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VmParameters) Reset() {
	*x = VmParameters{}
	mi := &file_proto_codiovmrange_codiovmrange_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VmParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VmParameters) ProtoMessage() {}

func (x *VmParameters) ProtoReflect() protoreflect.Message {
	mi := &file_proto_codiovmrange_codiovmrange_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VmParameters.ProtoReflect.Descriptor instead.
func (*VmParameters) Descriptor() ([]byte, []int) {
	return file_proto_codiovmrange_codiovmrange_service_proto_rawDescGZIP(), []int{11}
}

func (x *VmParameters) GetCpus() *wrapperspb.Int32Value {
	if x != nil {
		return x.Cpus
	}
	return nil
}

func (x *VmParameters) GetMemory() *VmParameters_Memory {
	if x != nil {
		return x.Memory
	}
	return nil
}

type SetParamsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Params        *VmParameters          `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetParamsRequest) Reset() {
	*x = SetParamsRequest{}
	mi := &file_proto_codiovmrange_codiovmrange_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetParamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetParamsRequest) ProtoMessage() {}

func (x *SetParamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_codiovmrange_codiovmrange_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetParamsRequest.ProtoReflect.Descriptor instead.
func (*SetParamsRequest) Descriptor() ([]byte, []int) {
	return file_proto_codiovmrange_codiovmrange_service_proto_rawDescGZIP(), []int{12}
}

func (x *SetParamsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SetParamsRequest) GetParams() *VmParameters {
	if x != nil {
		return x.Params
	}
	return nil
}

type SetParamsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetParamsResponse) Reset() {
	*x = SetParamsResponse{}
	mi := &file_proto_codiovmrange_codiovmrange_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetParamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetParamsResponse) ProtoMessage() {}

func (x *SetParamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_codiovmrange_codiovmrange_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetParamsResponse.ProtoReflect.Descriptor instead.
func (*SetParamsResponse) Descriptor() ([]byte, []int) {
	return file_proto_codiovmrange_codiovmrange_service_proto_rawDescGZIP(), []int{13}
}

type CreateVmResponse_CreateVmError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVmResponse_CreateVmError) Reset() {
	*x = CreateVmResponse_CreateVmError{}
	mi := &file_proto_codiovmrange_codiovmrange_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVmResponse_CreateVmError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVmResponse_CreateVmError) ProtoMessage() {}

func (x *CreateVmResponse_CreateVmError) ProtoReflect() protoreflect.Message {
	mi := &file_proto_codiovmrange_codiovmrange_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVmResponse_CreateVmError.ProtoReflect.Descriptor instead.
func (*CreateVmResponse_CreateVmError) Descriptor() ([]byte, []int) {
	return file_proto_codiovmrange_codiovmrange_service_proto_rawDescGZIP(), []int{1, 0}
}

func (x *CreateVmResponse_CreateVmError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CreateVmResponse_CreateVmCompleted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVmResponse_CreateVmCompleted) Reset() {
	*x = CreateVmResponse_CreateVmCompleted{}
	mi := &file_proto_codiovmrange_codiovmrange_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVmResponse_CreateVmCompleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVmResponse_CreateVmCompleted) ProtoMessage() {}

func (x *CreateVmResponse_CreateVmCompleted) ProtoReflect() protoreflect.Message {
	mi := &file_proto_codiovmrange_codiovmrange_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVmResponse_CreateVmCompleted.ProtoReflect.Descriptor instead.
func (*CreateVmResponse_CreateVmCompleted) Descriptor() ([]byte, []int) {
	return file_proto_codiovmrange_codiovmrange_service_proto_rawDescGZIP(), []int{1, 1}
}

type CreateVmResponse_CreateVmProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Progress      int32                  `protobuf:"varint,1,opt,name=progress,proto3" json:"progress,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVmResponse_CreateVmProgress) Reset() {
	*x = CreateVmResponse_CreateVmProgress{}
	mi := &file_proto_codiovmrange_codiovmrange_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVmResponse_CreateVmProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVmResponse_CreateVmProgress) ProtoMessage() {}

func (x *CreateVmResponse_CreateVmProgress) ProtoReflect() protoreflect.Message {
	mi := &file_proto_codiovmrange_codiovmrange_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVmResponse_CreateVmProgress.ProtoReflect.Descriptor instead.
func (*CreateVmResponse_CreateVmProgress) Descriptor() ([]byte, []int) {
	return file_proto_codiovmrange_codiovmrange_service_proto_rawDescGZIP(), []int{1, 2}
}

func (x *CreateVmResponse_CreateVmProgress) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *CreateVmResponse_CreateVmProgress) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type VmParameters_Memory struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Value         uint32                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Unit          VmParameters_MemoryUnit `protobuf:"varint,2,opt,name=unit,proto3,enum=com.codio.chipmunk.proto.codiovmrange.VmParameters_MemoryUnit" json:"unit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VmParameters_Memory) Reset() {
	*x = VmParameters_Memory{}
	mi := &file_proto_codiovmrange_codiovmrange_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VmParameters_Memory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VmParameters_Memory) ProtoMessage() {}

func (x *VmParameters_Memory) ProtoReflect() protoreflect.Message {
	mi := &file_proto_codiovmrange_codiovmrange_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VmParameters_Memory.ProtoReflect.Descriptor instead.
func (*VmParameters_Memory) Descriptor() ([]byte, []int) {
	return file_proto_codiovmrange_codiovmrange_service_proto_rawDescGZIP(), []int{11, 0}
}

func (x *VmParameters_Memory) GetValue() uint32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *VmParameters_Memory) GetUnit() VmParameters_MemoryUnit {
	if x != nil {
		return x.Unit
	}
	return VmParameters_KiB
}

var File_proto_codiovmrange_codiovmrange_service_proto protoreflect.FileDescriptor

const file_proto_codiovmrange_codiovmrange_service_proto_rawDesc = "" +
	"\n" +
	"-proto/codiovmrange/codiovmrange_service.proto\x12%com.codio.chipmunk.proto.codiovmrange\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"l\n" +
	"\x0fCreateVmRequest\x12\x1d\n" +
	"\n" +
	"image_name\x18\x01 \x01(\tR\timageName\x12\x1b\n" +
	"\timage_url\x18\x02 \x01(\tR\bimageUrl\x12\x1d\n" +
	"\n" +
	"domain_xml\x18\x03 \x01(\tR\tdomainXml\"\xd6\x03\n" +
	"\x10CreateVmResponse\x12]\n" +
	"\x05error\x18\x01 \x01(\v2E.com.codio.chipmunk.proto.codiovmrange.CreateVmResponse.CreateVmErrorH\x00R\x05error\x12i\n" +
	"\tcompleted\x18\x02 \x01(\v2I.com.codio.chipmunk.proto.codiovmrange.CreateVmResponse.CreateVmCompletedH\x00R\tcompleted\x12f\n" +
	"\bprogress\x18\x03 \x01(\v2H.com.codio.chipmunk.proto.codiovmrange.CreateVmResponse.CreateVmProgressH\x00R\bprogress\x1a)\n" +
	"\rCreateVmError\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x1a\x13\n" +
	"\x11CreateVmCompleted\x1aF\n" +
	"\x10CreateVmProgress\x12\x1a\n" +
	"\bprogress\x18\x01 \x01(\x05R\bprogress\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06statusB\b\n" +
	"\x06status\"\x10\n" +
	"\x0eListVmsRequest\"q\n" +
	"\x02Vm\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12G\n" +
	"\x06status\x18\x03 \x01(\x0e2/.com.codio.chipmunk.proto.codiovmrange.VmStatusR\x06status\"N\n" +
	"\x0fListVmsResponse\x12;\n" +
	"\x03vms\x18\x01 \x03(\v2).com.codio.chipmunk.proto.codiovmrange.VmR\x03vms\" \n" +
	"\x0eStartVmRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x11\n" +
	"\x0fStartVmResponse\"\x1f\n" +
	"\rStopVmRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x10\n" +
	"\x0eStopVmResponse\"\"\n" +
	"\x10DestroyVmRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x13\n" +
	"\x11DestroyVmResponse\"\xb0\x02\n" +
	"\fVmParameters\x12/\n" +
	"\x04cpus\x18\x01 \x01(\v2\x1b.google.protobuf.Int32ValueR\x04cpus\x12R\n" +
	"\x06memory\x18\x02 \x01(\v2:.com.codio.chipmunk.proto.codiovmrange.VmParameters.MemoryR\x06memory\x1ar\n" +
	"\x06Memory\x12\x14\n" +
	"\x05value\x18\x01 \x01(\rR\x05value\x12R\n" +
	"\x04unit\x18\x02 \x01(\x0e2>.com.codio.chipmunk.proto.codiovmrange.VmParameters.MemoryUnitR\x04unit\"'\n" +
	"\n" +
	"MemoryUnit\x12\a\n" +
	"\x03KiB\x10\x00\x12\a\n" +
	"\x03MiB\x10\x01\x12\a\n" +
	"\x03GiB\x10\x02\"o\n" +
	"\x10SetParamsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12K\n" +
	"\x06params\x18\x02 \x01(\v23.com.codio.chipmunk.proto.codiovmrange.VmParametersR\x06params\"\x13\n" +
	"\x11SetParamsResponse*$\n" +
	"\bVmStatus\x12\v\n" +
	"\aSTOPPED\x10\x00\x12\v\n" +
	"\aRUNNING\x10\x012\xf8\x05\n" +
	"\fCodioVmRange\x12}\n" +
	"\bCreateVm\x126.com.codio.chipmunk.proto.codiovmrange.CreateVmRequest\x1a7.com.codio.chipmunk.proto.codiovmrange.CreateVmResponse0\x01\x12x\n" +
	"\aStartVm\x125.com.codio.chipmunk.proto.codiovmrange.StartVmRequest\x1a6.com.codio.chipmunk.proto.codiovmrange.StartVmResponse\x12u\n" +
	"\x06StopVm\x124.com.codio.chipmunk.proto.codiovmrange.StopVmRequest\x1a5.com.codio.chipmunk.proto.codiovmrange.StopVmResponse\x12~\n" +
	"\tDestroyVm\x127.com.codio.chipmunk.proto.codiovmrange.DestroyVmRequest\x1a8.com.codio.chipmunk.proto.codiovmrange.DestroyVmResponse\x12~\n" +
	"\tSetParams\x127.com.codio.chipmunk.proto.codiovmrange.SetParamsRequest\x1a8.com.codio.chipmunk.proto.codiovmrange.SetParamsResponse\x12x\n" +
	"\aListVms\x125.com.codio.chipmunk.proto.codiovmrange.ListVmsRequest\x1a6.com.codio.chipmunk.proto.codiovmrange.ListVmsResponseB<Z:github.com/codio/chipmunk-interface-gen/proto/codiovmrangeb\x06proto3"

var (
	file_proto_codiovmrange_codiovmrange_service_proto_rawDescOnce sync.Once
	file_proto_codiovmrange_codiovmrange_service_proto_rawDescData []byte
)

func file_proto_codiovmrange_codiovmrange_service_proto_rawDescGZIP() []byte {
	file_proto_codiovmrange_codiovmrange_service_proto_rawDescOnce.Do(func() {
		file_proto_codiovmrange_codiovmrange_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_codiovmrange_codiovmrange_service_proto_rawDesc), len(file_proto_codiovmrange_codiovmrange_service_proto_rawDesc)))
	})
	return file_proto_codiovmrange_codiovmrange_service_proto_rawDescData
}

var file_proto_codiovmrange_codiovmrange_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_codiovmrange_codiovmrange_service_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_proto_codiovmrange_codiovmrange_service_proto_goTypes = []any{
	(VmStatus)(0),                              // 0: com.codio.chipmunk.proto.codiovmrange.VmStatus
	(VmParameters_MemoryUnit)(0),               // 1: com.codio.chipmunk.proto.codiovmrange.VmParameters.MemoryUnit
	(*CreateVmRequest)(nil),                    // 2: com.codio.chipmunk.proto.codiovmrange.CreateVmRequest
	(*CreateVmResponse)(nil),                   // 3: com.codio.chipmunk.proto.codiovmrange.CreateVmResponse
	(*ListVmsRequest)(nil),                     // 4: com.codio.chipmunk.proto.codiovmrange.ListVmsRequest
	(*Vm)(nil),                                 // 5: com.codio.chipmunk.proto.codiovmrange.Vm
	(*ListVmsResponse)(nil),                    // 6: com.codio.chipmunk.proto.codiovmrange.ListVmsResponse
	(*StartVmRequest)(nil),                     // 7: com.codio.chipmunk.proto.codiovmrange.StartVmRequest
	(*StartVmResponse)(nil),                    // 8: com.codio.chipmunk.proto.codiovmrange.StartVmResponse
	(*StopVmRequest)(nil),                      // 9: com.codio.chipmunk.proto.codiovmrange.StopVmRequest
	(*StopVmResponse)(nil),                     // 10: com.codio.chipmunk.proto.codiovmrange.StopVmResponse
	(*DestroyVmRequest)(nil),                   // 11: com.codio.chipmunk.proto.codiovmrange.DestroyVmRequest
	(*DestroyVmResponse)(nil),                  // 12: com.codio.chipmunk.proto.codiovmrange.DestroyVmResponse
	(*VmParameters)(nil),                       // 13: com.codio.chipmunk.proto.codiovmrange.VmParameters
	(*SetParamsRequest)(nil),                   // 14: com.codio.chipmunk.proto.codiovmrange.SetParamsRequest
	(*SetParamsResponse)(nil),                  // 15: com.codio.chipmunk.proto.codiovmrange.SetParamsResponse
	(*CreateVmResponse_CreateVmError)(nil),     // 16: com.codio.chipmunk.proto.codiovmrange.CreateVmResponse.CreateVmError
	(*CreateVmResponse_CreateVmCompleted)(nil), // 17: com.codio.chipmunk.proto.codiovmrange.CreateVmResponse.CreateVmCompleted
	(*CreateVmResponse_CreateVmProgress)(nil),  // 18: com.codio.chipmunk.proto.codiovmrange.CreateVmResponse.CreateVmProgress
	(*VmParameters_Memory)(nil),                // 19: com.codio.chipmunk.proto.codiovmrange.VmParameters.Memory
	(*wrapperspb.Int32Value)(nil),              // 20: google.protobuf.Int32Value
}
var file_proto_codiovmrange_codiovmrange_service_proto_depIdxs = []int32{
	16, // 0: com.codio.chipmunk.proto.codiovmrange.CreateVmResponse.error:type_name -> com.codio.chipmunk.proto.codiovmrange.CreateVmResponse.CreateVmError
	17, // 1: com.codio.chipmunk.proto.codiovmrange.CreateVmResponse.completed:type_name -> com.codio.chipmunk.proto.codiovmrange.CreateVmResponse.CreateVmCompleted
	18, // 2: com.codio.chipmunk.proto.codiovmrange.CreateVmResponse.progress:type_name -> com.codio.chipmunk.proto.codiovmrange.CreateVmResponse.CreateVmProgress
	0,  // 3: com.codio.chipmunk.proto.codiovmrange.Vm.status:type_name -> com.codio.chipmunk.proto.codiovmrange.VmStatus
	5,  // 4: com.codio.chipmunk.proto.codiovmrange.ListVmsResponse.vms:type_name -> com.codio.chipmunk.proto.codiovmrange.Vm
	20, // 5: com.codio.chipmunk.proto.codiovmrange.VmParameters.cpus:type_name -> google.protobuf.Int32Value
	19, // 6: com.codio.chipmunk.proto.codiovmrange.VmParameters.memory:type_name -> com.codio.chipmunk.proto.codiovmrange.VmParameters.Memory
	13, // 7: com.codio.chipmunk.proto.codiovmrange.SetParamsRequest.params:type_name -> com.codio.chipmunk.proto.codiovmrange.VmParameters
	1,  // 8: com.codio.chipmunk.proto.codiovmrange.VmParameters.Memory.unit:type_name -> com.codio.chipmunk.proto.codiovmrange.VmParameters.MemoryUnit
	2,  // 9: com.codio.chipmunk.proto.codiovmrange.CodioVmRange.CreateVm:input_type -> com.codio.chipmunk.proto.codiovmrange.CreateVmRequest
	7,  // 10: com.codio.chipmunk.proto.codiovmrange.CodioVmRange.StartVm:input_type -> com.codio.chipmunk.proto.codiovmrange.StartVmRequest
	9,  // 11: com.codio.chipmunk.proto.codiovmrange.CodioVmRange.StopVm:input_type -> com.codio.chipmunk.proto.codiovmrange.StopVmRequest
	11, // 12: com.codio.chipmunk.proto.codiovmrange.CodioVmRange.DestroyVm:input_type -> com.codio.chipmunk.proto.codiovmrange.DestroyVmRequest
	14, // 13: com.codio.chipmunk.proto.codiovmrange.CodioVmRange.SetParams:input_type -> com.codio.chipmunk.proto.codiovmrange.SetParamsRequest
	4,  // 14: com.codio.chipmunk.proto.codiovmrange.CodioVmRange.ListVms:input_type -> com.codio.chipmunk.proto.codiovmrange.ListVmsRequest
	3,  // 15: com.codio.chipmunk.proto.codiovmrange.CodioVmRange.CreateVm:output_type -> com.codio.chipmunk.proto.codiovmrange.CreateVmResponse
	8,  // 16: com.codio.chipmunk.proto.codiovmrange.CodioVmRange.StartVm:output_type -> com.codio.chipmunk.proto.codiovmrange.StartVmResponse
	10, // 17: com.codio.chipmunk.proto.codiovmrange.CodioVmRange.StopVm:output_type -> com.codio.chipmunk.proto.codiovmrange.StopVmResponse
	12, // 18: com.codio.chipmunk.proto.codiovmrange.CodioVmRange.DestroyVm:output_type -> com.codio.chipmunk.proto.codiovmrange.DestroyVmResponse
	15, // 19: com.codio.chipmunk.proto.codiovmrange.CodioVmRange.SetParams:output_type -> com.codio.chipmunk.proto.codiovmrange.SetParamsResponse
	6,  // 20: com.codio.chipmunk.proto.codiovmrange.CodioVmRange.ListVms:output_type -> com.codio.chipmunk.proto.codiovmrange.ListVmsResponse
	15, // [15:21] is the sub-list for method output_type
	9,  // [9:15] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_codiovmrange_codiovmrange_service_proto_init() }
func file_proto_codiovmrange_codiovmrange_service_proto_init() {
	if File_proto_codiovmrange_codiovmrange_service_proto != nil {
		return
	}
	file_proto_codiovmrange_codiovmrange_service_proto_msgTypes[1].OneofWrappers = []any{
		(*CreateVmResponse_Error)(nil),
		(*CreateVmResponse_Completed)(nil),
		(*CreateVmResponse_Progress)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_codiovmrange_codiovmrange_service_proto_rawDesc), len(file_proto_codiovmrange_codiovmrange_service_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_codiovmrange_codiovmrange_service_proto_goTypes,
		DependencyIndexes: file_proto_codiovmrange_codiovmrange_service_proto_depIdxs,
		EnumInfos:         file_proto_codiovmrange_codiovmrange_service_proto_enumTypes,
		MessageInfos:      file_proto_codiovmrange_codiovmrange_service_proto_msgTypes,
	}.Build()
	File_proto_codiovmrange_codiovmrange_service_proto = out.File
	file_proto_codiovmrange_codiovmrange_service_proto_goTypes = nil
	file_proto_codiovmrange_codiovmrange_service_proto_depIdxs = nil
}
