// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v4.23.4
// source: proto/codiovmrange/codiovmrange_service.proto

package codiovmrange

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VmStatus int32

const (
	VmStatus_STOPPED VmStatus = 0
	VmStatus_RUNNING VmStatus = 1
)

// Enum value maps for VmStatus.
var (
	VmStatus_name = map[int32]string{
		0: "STOPPED",
		1: "RUNNING",
	}
	VmStatus_value = map[string]int32{
		"STOPPED": 0,
		"RUNNING": 1,
	}
)

func (x VmStatus) Enum() *VmStatus {
	p := new(VmStatus)
	*p = x
	return p
}

func (x VmStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VmStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_codiovmrange_codiovmrange_service_proto_enumTypes[0].Descriptor()
}

func (VmStatus) Type() protoreflect.EnumType {
	return &file_proto_codiovmrange_codiovmrange_service_proto_enumTypes[0]
}

func (x VmStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VmStatus.Descriptor instead.
func (VmStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_codiovmrange_codiovmrange_service_proto_rawDescGZIP(), []int{0}
}

type CreateVmRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ImageName string `protobuf:"bytes,1,opt,name=image_name,json=imageName,proto3" json:"image_name,omitempty"`
	ImageUrl  string `protobuf:"bytes,2,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	DomainXml string `protobuf:"bytes,3,opt,name=domain_xml,json=domainXml,proto3" json:"domain_xml,omitempty"`
}

func (x *CreateVmRequest) Reset() {
	*x = CreateVmRequest{}
	mi := &file_proto_codiovmrange_codiovmrange_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVmRequest) ProtoMessage() {}

func (x *CreateVmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_codiovmrange_codiovmrange_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVmRequest.ProtoReflect.Descriptor instead.
func (*CreateVmRequest) Descriptor() ([]byte, []int) {
	return file_proto_codiovmrange_codiovmrange_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateVmRequest) GetImageName() string {
	if x != nil {
		return x.ImageName
	}
	return ""
}

func (x *CreateVmRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *CreateVmRequest) GetDomainXml() string {
	if x != nil {
		return x.DomainXml
	}
	return ""
}

type CreateVmResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Status:
	//
	//	*CreateVmResponse_Error
	//	*CreateVmResponse_Completed
	//	*CreateVmResponse_Progress
	Status isCreateVmResponse_Status `protobuf_oneof:"status"`
}

func (x *CreateVmResponse) Reset() {
	*x = CreateVmResponse{}
	mi := &file_proto_codiovmrange_codiovmrange_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVmResponse) ProtoMessage() {}

func (x *CreateVmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_codiovmrange_codiovmrange_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVmResponse.ProtoReflect.Descriptor instead.
func (*CreateVmResponse) Descriptor() ([]byte, []int) {
	return file_proto_codiovmrange_codiovmrange_service_proto_rawDescGZIP(), []int{1}
}

func (m *CreateVmResponse) GetStatus() isCreateVmResponse_Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (x *CreateVmResponse) GetError() *CreateVmResponse_CreateVmError {
	if x, ok := x.GetStatus().(*CreateVmResponse_Error); ok {
		return x.Error
	}
	return nil
}

func (x *CreateVmResponse) GetCompleted() *CreateVmResponse_CreateVmCompleted {
	if x, ok := x.GetStatus().(*CreateVmResponse_Completed); ok {
		return x.Completed
	}
	return nil
}

func (x *CreateVmResponse) GetProgress() *CreateVmResponse_CreateVmProgress {
	if x, ok := x.GetStatus().(*CreateVmResponse_Progress); ok {
		return x.Progress
	}
	return nil
}

type isCreateVmResponse_Status interface {
	isCreateVmResponse_Status()
}

type CreateVmResponse_Error struct {
	Error *CreateVmResponse_CreateVmError `protobuf:"bytes,1,opt,name=error,proto3,oneof"`
}

type CreateVmResponse_Completed struct {
	Completed *CreateVmResponse_CreateVmCompleted `protobuf:"bytes,2,opt,name=completed,proto3,oneof"`
}

type CreateVmResponse_Progress struct {
	Progress *CreateVmResponse_CreateVmProgress `protobuf:"bytes,3,opt,name=progress,proto3,oneof"`
}

func (*CreateVmResponse_Error) isCreateVmResponse_Status() {}

func (*CreateVmResponse_Completed) isCreateVmResponse_Status() {}

func (*CreateVmResponse_Progress) isCreateVmResponse_Status() {}

type ListVmsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListVmsRequest) Reset() {
	*x = ListVmsRequest{}
	mi := &file_proto_codiovmrange_codiovmrange_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVmsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVmsRequest) ProtoMessage() {}

func (x *ListVmsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_codiovmrange_codiovmrange_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVmsRequest.ProtoReflect.Descriptor instead.
func (*ListVmsRequest) Descriptor() ([]byte, []int) {
	return file_proto_codiovmrange_codiovmrange_service_proto_rawDescGZIP(), []int{2}
}

type Vm struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name   string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status VmStatus `protobuf:"varint,3,opt,name=status,proto3,enum=com.codio.chipmunk.proto.codiovmrange.VmStatus" json:"status,omitempty"`
}

func (x *Vm) Reset() {
	*x = Vm{}
	mi := &file_proto_codiovmrange_codiovmrange_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vm) ProtoMessage() {}

func (x *Vm) ProtoReflect() protoreflect.Message {
	mi := &file_proto_codiovmrange_codiovmrange_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vm.ProtoReflect.Descriptor instead.
func (*Vm) Descriptor() ([]byte, []int) {
	return file_proto_codiovmrange_codiovmrange_service_proto_rawDescGZIP(), []int{3}
}

func (x *Vm) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Vm) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Vm) GetStatus() VmStatus {
	if x != nil {
		return x.Status
	}
	return VmStatus_STOPPED
}

type ListVmsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vms []*Vm `protobuf:"bytes,1,rep,name=vms,proto3" json:"vms,omitempty"`
}

func (x *ListVmsResponse) Reset() {
	*x = ListVmsResponse{}
	mi := &file_proto_codiovmrange_codiovmrange_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVmsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVmsResponse) ProtoMessage() {}

func (x *ListVmsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_codiovmrange_codiovmrange_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVmsResponse.ProtoReflect.Descriptor instead.
func (*ListVmsResponse) Descriptor() ([]byte, []int) {
	return file_proto_codiovmrange_codiovmrange_service_proto_rawDescGZIP(), []int{4}
}

func (x *ListVmsResponse) GetVms() []*Vm {
	if x != nil {
		return x.Vms
	}
	return nil
}

type StartVmRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *StartVmRequest) Reset() {
	*x = StartVmRequest{}
	mi := &file_proto_codiovmrange_codiovmrange_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartVmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartVmRequest) ProtoMessage() {}

func (x *StartVmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_codiovmrange_codiovmrange_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartVmRequest.ProtoReflect.Descriptor instead.
func (*StartVmRequest) Descriptor() ([]byte, []int) {
	return file_proto_codiovmrange_codiovmrange_service_proto_rawDescGZIP(), []int{5}
}

func (x *StartVmRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type StartVmResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StartVmResponse) Reset() {
	*x = StartVmResponse{}
	mi := &file_proto_codiovmrange_codiovmrange_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartVmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartVmResponse) ProtoMessage() {}

func (x *StartVmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_codiovmrange_codiovmrange_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartVmResponse.ProtoReflect.Descriptor instead.
func (*StartVmResponse) Descriptor() ([]byte, []int) {
	return file_proto_codiovmrange_codiovmrange_service_proto_rawDescGZIP(), []int{6}
}

type StopVmRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *StopVmRequest) Reset() {
	*x = StopVmRequest{}
	mi := &file_proto_codiovmrange_codiovmrange_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopVmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopVmRequest) ProtoMessage() {}

func (x *StopVmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_codiovmrange_codiovmrange_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopVmRequest.ProtoReflect.Descriptor instead.
func (*StopVmRequest) Descriptor() ([]byte, []int) {
	return file_proto_codiovmrange_codiovmrange_service_proto_rawDescGZIP(), []int{7}
}

func (x *StopVmRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type StopVmResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StopVmResponse) Reset() {
	*x = StopVmResponse{}
	mi := &file_proto_codiovmrange_codiovmrange_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopVmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopVmResponse) ProtoMessage() {}

func (x *StopVmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_codiovmrange_codiovmrange_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopVmResponse.ProtoReflect.Descriptor instead.
func (*StopVmResponse) Descriptor() ([]byte, []int) {
	return file_proto_codiovmrange_codiovmrange_service_proto_rawDescGZIP(), []int{8}
}

type DestroyVmRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DestroyVmRequest) Reset() {
	*x = DestroyVmRequest{}
	mi := &file_proto_codiovmrange_codiovmrange_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyVmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyVmRequest) ProtoMessage() {}

func (x *DestroyVmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_codiovmrange_codiovmrange_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyVmRequest.ProtoReflect.Descriptor instead.
func (*DestroyVmRequest) Descriptor() ([]byte, []int) {
	return file_proto_codiovmrange_codiovmrange_service_proto_rawDescGZIP(), []int{9}
}

func (x *DestroyVmRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DestroyVmResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DestroyVmResponse) Reset() {
	*x = DestroyVmResponse{}
	mi := &file_proto_codiovmrange_codiovmrange_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyVmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyVmResponse) ProtoMessage() {}

func (x *DestroyVmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_codiovmrange_codiovmrange_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyVmResponse.ProtoReflect.Descriptor instead.
func (*DestroyVmResponse) Descriptor() ([]byte, []int) {
	return file_proto_codiovmrange_codiovmrange_service_proto_rawDescGZIP(), []int{10}
}

type CreateVmResponse_CreateVmError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *CreateVmResponse_CreateVmError) Reset() {
	*x = CreateVmResponse_CreateVmError{}
	mi := &file_proto_codiovmrange_codiovmrange_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVmResponse_CreateVmError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVmResponse_CreateVmError) ProtoMessage() {}

func (x *CreateVmResponse_CreateVmError) ProtoReflect() protoreflect.Message {
	mi := &file_proto_codiovmrange_codiovmrange_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVmResponse_CreateVmError.ProtoReflect.Descriptor instead.
func (*CreateVmResponse_CreateVmError) Descriptor() ([]byte, []int) {
	return file_proto_codiovmrange_codiovmrange_service_proto_rawDescGZIP(), []int{1, 0}
}

func (x *CreateVmResponse_CreateVmError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CreateVmResponse_CreateVmCompleted struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateVmResponse_CreateVmCompleted) Reset() {
	*x = CreateVmResponse_CreateVmCompleted{}
	mi := &file_proto_codiovmrange_codiovmrange_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVmResponse_CreateVmCompleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVmResponse_CreateVmCompleted) ProtoMessage() {}

func (x *CreateVmResponse_CreateVmCompleted) ProtoReflect() protoreflect.Message {
	mi := &file_proto_codiovmrange_codiovmrange_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVmResponse_CreateVmCompleted.ProtoReflect.Descriptor instead.
func (*CreateVmResponse_CreateVmCompleted) Descriptor() ([]byte, []int) {
	return file_proto_codiovmrange_codiovmrange_service_proto_rawDescGZIP(), []int{1, 1}
}

type CreateVmResponse_CreateVmProgress struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Progress int32 `protobuf:"varint,1,opt,name=progress,proto3" json:"progress,omitempty"`
}

func (x *CreateVmResponse_CreateVmProgress) Reset() {
	*x = CreateVmResponse_CreateVmProgress{}
	mi := &file_proto_codiovmrange_codiovmrange_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVmResponse_CreateVmProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVmResponse_CreateVmProgress) ProtoMessage() {}

func (x *CreateVmResponse_CreateVmProgress) ProtoReflect() protoreflect.Message {
	mi := &file_proto_codiovmrange_codiovmrange_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVmResponse_CreateVmProgress.ProtoReflect.Descriptor instead.
func (*CreateVmResponse_CreateVmProgress) Descriptor() ([]byte, []int) {
	return file_proto_codiovmrange_codiovmrange_service_proto_rawDescGZIP(), []int{1, 2}
}

func (x *CreateVmResponse_CreateVmProgress) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

var File_proto_codiovmrange_codiovmrange_service_proto protoreflect.FileDescriptor

var file_proto_codiovmrange_codiovmrange_service_proto_rawDesc = []byte{
	0x0a, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x64, 0x69, 0x6f, 0x76, 0x6d, 0x72,
	0x61, 0x6e, 0x67, 0x65, 0x2f, 0x63, 0x6f, 0x64, 0x69, 0x6f, 0x76, 0x6d, 0x72, 0x61, 0x6e, 0x67,
	0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x25, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x6f, 0x64, 0x69, 0x6f, 0x2e, 0x63, 0x68, 0x69, 0x70, 0x6d,
	0x75, 0x6e, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x64, 0x69, 0x6f, 0x76,
	0x6d, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6c, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x56, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x6d,
	0x61, 0x67, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x69, 0x6d, 0x61, 0x67, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6d, 0x61,
	0x67, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6d,
	0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x1d, 0x0a, 0x0a, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e,
	0x5f, 0x78, 0x6d, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x64, 0x6f, 0x6d, 0x61,
	0x69, 0x6e, 0x58, 0x6d, 0x6c, 0x22, 0xbe, 0x03, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x56, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5d, 0x0a, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x45, 0x2e, 0x63, 0x6f, 0x6d, 0x2e,
	0x63, 0x6f, 0x64, 0x69, 0x6f, 0x2e, 0x63, 0x68, 0x69, 0x70, 0x6d, 0x75, 0x6e, 0x6b, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x64, 0x69, 0x6f, 0x76, 0x6d, 0x72, 0x61, 0x6e, 0x67,
	0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56, 0x6d, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x69, 0x0a, 0x09, 0x63, 0x6f, 0x6d,
	0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x49, 0x2e, 0x63,
	0x6f, 0x6d, 0x2e, 0x63, 0x6f, 0x64, 0x69, 0x6f, 0x2e, 0x63, 0x68, 0x69, 0x70, 0x6d, 0x75, 0x6e,
	0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x64, 0x69, 0x6f, 0x76, 0x6d, 0x72,
	0x61, 0x6e, 0x67, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56, 0x6d, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56, 0x6d, 0x43, 0x6f,
	0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x48, 0x00, 0x52, 0x09, 0x63, 0x6f, 0x6d, 0x70, 0x6c,
	0x65, 0x74, 0x65, 0x64, 0x12, 0x66, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x48, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x6f, 0x64,
	0x69, 0x6f, 0x2e, 0x63, 0x68, 0x69, 0x70, 0x6d, 0x75, 0x6e, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x63, 0x6f, 0x64, 0x69, 0x6f, 0x76, 0x6d, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x56, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56, 0x6d, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73,
	0x48, 0x00, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x1a, 0x29, 0x0a, 0x0d,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56, 0x6d, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x13, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x56, 0x6d, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x1a, 0x2e, 0x0a, 0x10,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56, 0x6d, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73,
	0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x42, 0x08, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x10, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x6d,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x71, 0x0a, 0x02, 0x56, 0x6d, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x47, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x2f, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x6f, 0x64, 0x69, 0x6f, 0x2e, 0x63,
	0x68, 0x69, 0x70, 0x6d, 0x75, 0x6e, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f,
	0x64, 0x69, 0x6f, 0x76, 0x6d, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x2e, 0x56, 0x6d, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x4e, 0x0a, 0x0f, 0x4c,
	0x69, 0x73, 0x74, 0x56, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b,
	0x0a, 0x03, 0x76, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x63, 0x6f,
	0x6d, 0x2e, 0x63, 0x6f, 0x64, 0x69, 0x6f, 0x2e, 0x63, 0x68, 0x69, 0x70, 0x6d, 0x75, 0x6e, 0x6b,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x64, 0x69, 0x6f, 0x76, 0x6d, 0x72, 0x61,
	0x6e, 0x67, 0x65, 0x2e, 0x56, 0x6d, 0x52, 0x03, 0x76, 0x6d, 0x73, 0x22, 0x20, 0x0a, 0x0e, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x56, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x11, 0x0a,
	0x0f, 0x53, 0x74, 0x61, 0x72, 0x74, 0x56, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x1f, 0x0a, 0x0d, 0x53, 0x74, 0x6f, 0x70, 0x56, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x10, 0x0a, 0x0e, 0x53, 0x74, 0x6f, 0x70, 0x56, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x22, 0x0a, 0x10, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x56, 0x6d,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x13, 0x0a, 0x11, 0x44, 0x65, 0x73, 0x74, 0x72,
	0x6f, 0x79, 0x56, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2a, 0x24, 0x0a, 0x08,
	0x56, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x54, 0x4f, 0x50,
	0x50, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x55, 0x4e, 0x4e, 0x49, 0x4e, 0x47,
	0x10, 0x01, 0x32, 0xf8, 0x04, 0x0a, 0x0c, 0x43, 0x6f, 0x64, 0x69, 0x6f, 0x56, 0x6d, 0x52, 0x61,
	0x6e, 0x67, 0x65, 0x12, 0x7d, 0x0a, 0x08, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56, 0x6d, 0x12,
	0x36, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x6f, 0x64, 0x69, 0x6f, 0x2e, 0x63, 0x68, 0x69, 0x70,
	0x6d, 0x75, 0x6e, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x64, 0x69, 0x6f,
	0x76, 0x6d, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56, 0x6d,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x37, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x6f,
	0x64, 0x69, 0x6f, 0x2e, 0x63, 0x68, 0x69, 0x70, 0x6d, 0x75, 0x6e, 0x6b, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x64, 0x69, 0x6f, 0x76, 0x6d, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x30, 0x01, 0x12, 0x78, 0x0a, 0x07, 0x53, 0x74, 0x61, 0x72, 0x74, 0x56, 0x6d, 0x12, 0x35, 0x2e,
	0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x6f, 0x64, 0x69, 0x6f, 0x2e, 0x63, 0x68, 0x69, 0x70, 0x6d, 0x75,
	0x6e, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x64, 0x69, 0x6f, 0x76, 0x6d,
	0x72, 0x61, 0x6e, 0x67, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x56, 0x6d, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x36, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x6f, 0x64, 0x69, 0x6f,
	0x2e, 0x63, 0x68, 0x69, 0x70, 0x6d, 0x75, 0x6e, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x63, 0x6f, 0x64, 0x69, 0x6f, 0x76, 0x6d, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x2e, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x56, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x75, 0x0a, 0x06,
	0x53, 0x74, 0x6f, 0x70, 0x56, 0x6d, 0x12, 0x34, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x6f, 0x64,
	0x69, 0x6f, 0x2e, 0x63, 0x68, 0x69, 0x70, 0x6d, 0x75, 0x6e, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x63, 0x6f, 0x64, 0x69, 0x6f, 0x76, 0x6d, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x2e, 0x53,
	0x74, 0x6f, 0x70, 0x56, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x35, 0x2e, 0x63,
	0x6f, 0x6d, 0x2e, 0x63, 0x6f, 0x64, 0x69, 0x6f, 0x2e, 0x63, 0x68, 0x69, 0x70, 0x6d, 0x75, 0x6e,
	0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x64, 0x69, 0x6f, 0x76, 0x6d, 0x72,
	0x61, 0x6e, 0x67, 0x65, 0x2e, 0x53, 0x74, 0x6f, 0x70, 0x56, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x7e, 0x0a, 0x09, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x56, 0x6d,
	0x12, 0x37, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x6f, 0x64, 0x69, 0x6f, 0x2e, 0x63, 0x68, 0x69,
	0x70, 0x6d, 0x75, 0x6e, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x64, 0x69,
	0x6f, 0x76, 0x6d, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x2e, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79,
	0x56, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x38, 0x2e, 0x63, 0x6f, 0x6d, 0x2e,
	0x63, 0x6f, 0x64, 0x69, 0x6f, 0x2e, 0x63, 0x68, 0x69, 0x70, 0x6d, 0x75, 0x6e, 0x6b, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x64, 0x69, 0x6f, 0x76, 0x6d, 0x72, 0x61, 0x6e, 0x67,
	0x65, 0x2e, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x56, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x78, 0x0a, 0x07, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x6d, 0x73, 0x12, 0x35,
	0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x6f, 0x64, 0x69, 0x6f, 0x2e, 0x63, 0x68, 0x69, 0x70, 0x6d,
	0x75, 0x6e, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x64, 0x69, 0x6f, 0x76,
	0x6d, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x6d, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x36, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x6f, 0x64, 0x69,
	0x6f, 0x2e, 0x63, 0x68, 0x69, 0x70, 0x6d, 0x75, 0x6e, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x63, 0x6f, 0x64, 0x69, 0x6f, 0x76, 0x6d, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x56, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x3c, 0x5a,
	0x3a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6f, 0x64, 0x69,
	0x6f, 0x2f, 0x63, 0x68, 0x69, 0x70, 0x6d, 0x75, 0x6e, 0x6b, 0x2d, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x66, 0x61, 0x63, 0x65, 0x2d, 0x67, 0x65, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63,
	0x6f, 0x64, 0x69, 0x6f, 0x76, 0x6d, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_proto_codiovmrange_codiovmrange_service_proto_rawDescOnce sync.Once
	file_proto_codiovmrange_codiovmrange_service_proto_rawDescData = file_proto_codiovmrange_codiovmrange_service_proto_rawDesc
)

func file_proto_codiovmrange_codiovmrange_service_proto_rawDescGZIP() []byte {
	file_proto_codiovmrange_codiovmrange_service_proto_rawDescOnce.Do(func() {
		file_proto_codiovmrange_codiovmrange_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_codiovmrange_codiovmrange_service_proto_rawDescData)
	})
	return file_proto_codiovmrange_codiovmrange_service_proto_rawDescData
}

var file_proto_codiovmrange_codiovmrange_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_codiovmrange_codiovmrange_service_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_codiovmrange_codiovmrange_service_proto_goTypes = []any{
	(VmStatus)(0),                              // 0: com.codio.chipmunk.proto.codiovmrange.VmStatus
	(*CreateVmRequest)(nil),                    // 1: com.codio.chipmunk.proto.codiovmrange.CreateVmRequest
	(*CreateVmResponse)(nil),                   // 2: com.codio.chipmunk.proto.codiovmrange.CreateVmResponse
	(*ListVmsRequest)(nil),                     // 3: com.codio.chipmunk.proto.codiovmrange.ListVmsRequest
	(*Vm)(nil),                                 // 4: com.codio.chipmunk.proto.codiovmrange.Vm
	(*ListVmsResponse)(nil),                    // 5: com.codio.chipmunk.proto.codiovmrange.ListVmsResponse
	(*StartVmRequest)(nil),                     // 6: com.codio.chipmunk.proto.codiovmrange.StartVmRequest
	(*StartVmResponse)(nil),                    // 7: com.codio.chipmunk.proto.codiovmrange.StartVmResponse
	(*StopVmRequest)(nil),                      // 8: com.codio.chipmunk.proto.codiovmrange.StopVmRequest
	(*StopVmResponse)(nil),                     // 9: com.codio.chipmunk.proto.codiovmrange.StopVmResponse
	(*DestroyVmRequest)(nil),                   // 10: com.codio.chipmunk.proto.codiovmrange.DestroyVmRequest
	(*DestroyVmResponse)(nil),                  // 11: com.codio.chipmunk.proto.codiovmrange.DestroyVmResponse
	(*CreateVmResponse_CreateVmError)(nil),     // 12: com.codio.chipmunk.proto.codiovmrange.CreateVmResponse.CreateVmError
	(*CreateVmResponse_CreateVmCompleted)(nil), // 13: com.codio.chipmunk.proto.codiovmrange.CreateVmResponse.CreateVmCompleted
	(*CreateVmResponse_CreateVmProgress)(nil),  // 14: com.codio.chipmunk.proto.codiovmrange.CreateVmResponse.CreateVmProgress
}
var file_proto_codiovmrange_codiovmrange_service_proto_depIdxs = []int32{
	12, // 0: com.codio.chipmunk.proto.codiovmrange.CreateVmResponse.error:type_name -> com.codio.chipmunk.proto.codiovmrange.CreateVmResponse.CreateVmError
	13, // 1: com.codio.chipmunk.proto.codiovmrange.CreateVmResponse.completed:type_name -> com.codio.chipmunk.proto.codiovmrange.CreateVmResponse.CreateVmCompleted
	14, // 2: com.codio.chipmunk.proto.codiovmrange.CreateVmResponse.progress:type_name -> com.codio.chipmunk.proto.codiovmrange.CreateVmResponse.CreateVmProgress
	0,  // 3: com.codio.chipmunk.proto.codiovmrange.Vm.status:type_name -> com.codio.chipmunk.proto.codiovmrange.VmStatus
	4,  // 4: com.codio.chipmunk.proto.codiovmrange.ListVmsResponse.vms:type_name -> com.codio.chipmunk.proto.codiovmrange.Vm
	1,  // 5: com.codio.chipmunk.proto.codiovmrange.CodioVmRange.CreateVm:input_type -> com.codio.chipmunk.proto.codiovmrange.CreateVmRequest
	6,  // 6: com.codio.chipmunk.proto.codiovmrange.CodioVmRange.StartVm:input_type -> com.codio.chipmunk.proto.codiovmrange.StartVmRequest
	8,  // 7: com.codio.chipmunk.proto.codiovmrange.CodioVmRange.StopVm:input_type -> com.codio.chipmunk.proto.codiovmrange.StopVmRequest
	10, // 8: com.codio.chipmunk.proto.codiovmrange.CodioVmRange.DestroyVm:input_type -> com.codio.chipmunk.proto.codiovmrange.DestroyVmRequest
	3,  // 9: com.codio.chipmunk.proto.codiovmrange.CodioVmRange.ListVms:input_type -> com.codio.chipmunk.proto.codiovmrange.ListVmsRequest
	2,  // 10: com.codio.chipmunk.proto.codiovmrange.CodioVmRange.CreateVm:output_type -> com.codio.chipmunk.proto.codiovmrange.CreateVmResponse
	7,  // 11: com.codio.chipmunk.proto.codiovmrange.CodioVmRange.StartVm:output_type -> com.codio.chipmunk.proto.codiovmrange.StartVmResponse
	9,  // 12: com.codio.chipmunk.proto.codiovmrange.CodioVmRange.StopVm:output_type -> com.codio.chipmunk.proto.codiovmrange.StopVmResponse
	11, // 13: com.codio.chipmunk.proto.codiovmrange.CodioVmRange.DestroyVm:output_type -> com.codio.chipmunk.proto.codiovmrange.DestroyVmResponse
	5,  // 14: com.codio.chipmunk.proto.codiovmrange.CodioVmRange.ListVms:output_type -> com.codio.chipmunk.proto.codiovmrange.ListVmsResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_codiovmrange_codiovmrange_service_proto_init() }
func file_proto_codiovmrange_codiovmrange_service_proto_init() {
	if File_proto_codiovmrange_codiovmrange_service_proto != nil {
		return
	}
	file_proto_codiovmrange_codiovmrange_service_proto_msgTypes[1].OneofWrappers = []any{
		(*CreateVmResponse_Error)(nil),
		(*CreateVmResponse_Completed)(nil),
		(*CreateVmResponse_Progress)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_codiovmrange_codiovmrange_service_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_codiovmrange_codiovmrange_service_proto_goTypes,
		DependencyIndexes: file_proto_codiovmrange_codiovmrange_service_proto_depIdxs,
		EnumInfos:         file_proto_codiovmrange_codiovmrange_service_proto_enumTypes,
		MessageInfos:      file_proto_codiovmrange_codiovmrange_service_proto_msgTypes,
	}.Build()
	File_proto_codiovmrange_codiovmrange_service_proto = out.File
	file_proto_codiovmrange_codiovmrange_service_proto_rawDesc = nil
	file_proto_codiovmrange_codiovmrange_service_proto_goTypes = nil
	file_proto_codiovmrange_codiovmrange_service_proto_depIdxs = nil
}
