// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.23.4
// source: proto/common/common_service.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ForceUpdateConfigRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CodioDomain        string                 `protobuf:"bytes,1,opt,name=codio_domain,json=codioDomain,proto3" json:"codio_domain,omitempty"`
	VmDomain           string                 `protobuf:"bytes,2,opt,name=vm_domain,json=vmDomain,proto3" json:"vm_domain,omitempty"`
	NoVncClientVersion string                 `protobuf:"bytes,3,opt,name=no_vnc_client_version,json=noVncClientVersion,proto3" json:"no_vnc_client_version,omitempty"`
	Branch             string                 `protobuf:"bytes,4,opt,name=branch,proto3" json:"branch,omitempty"`
	SignSecret         string                 `protobuf:"bytes,5,opt,name=sign_secret,json=signSecret,proto3" json:"sign_secret,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ForceUpdateConfigRequest) Reset() {
	*x = ForceUpdateConfigRequest{}
	mi := &file_proto_common_common_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForceUpdateConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForceUpdateConfigRequest) ProtoMessage() {}

func (x *ForceUpdateConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_common_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForceUpdateConfigRequest.ProtoReflect.Descriptor instead.
func (*ForceUpdateConfigRequest) Descriptor() ([]byte, []int) {
	return file_proto_common_common_service_proto_rawDescGZIP(), []int{0}
}

func (x *ForceUpdateConfigRequest) GetCodioDomain() string {
	if x != nil {
		return x.CodioDomain
	}
	return ""
}

func (x *ForceUpdateConfigRequest) GetVmDomain() string {
	if x != nil {
		return x.VmDomain
	}
	return ""
}

func (x *ForceUpdateConfigRequest) GetNoVncClientVersion() string {
	if x != nil {
		return x.NoVncClientVersion
	}
	return ""
}

func (x *ForceUpdateConfigRequest) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *ForceUpdateConfigRequest) GetSignSecret() string {
	if x != nil {
		return x.SignSecret
	}
	return ""
}

type ForceUpdateConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForceUpdateConfigResponse) Reset() {
	*x = ForceUpdateConfigResponse{}
	mi := &file_proto_common_common_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForceUpdateConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForceUpdateConfigResponse) ProtoMessage() {}

func (x *ForceUpdateConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_common_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForceUpdateConfigResponse.ProtoReflect.Descriptor instead.
func (*ForceUpdateConfigResponse) Descriptor() ([]byte, []int) {
	return file_proto_common_common_service_proto_rawDescGZIP(), []int{1}
}

type GetChipmunkVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChipmunkVersionRequest) Reset() {
	*x = GetChipmunkVersionRequest{}
	mi := &file_proto_common_common_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChipmunkVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChipmunkVersionRequest) ProtoMessage() {}

func (x *GetChipmunkVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_common_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChipmunkVersionRequest.ProtoReflect.Descriptor instead.
func (*GetChipmunkVersionRequest) Descriptor() ([]byte, []int) {
	return file_proto_common_common_service_proto_rawDescGZIP(), []int{2}
}

type GetChipmunkVersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChipmunkVersionResponse) Reset() {
	*x = GetChipmunkVersionResponse{}
	mi := &file_proto_common_common_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChipmunkVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChipmunkVersionResponse) ProtoMessage() {}

func (x *GetChipmunkVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_common_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChipmunkVersionResponse.ProtoReflect.Descriptor instead.
func (*GetChipmunkVersionResponse) Descriptor() ([]byte, []int) {
	return file_proto_common_common_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetChipmunkVersionResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_proto_common_common_service_proto protoreflect.FileDescriptor

const file_proto_common_common_service_proto_rawDesc = "" +
	"\n" +
	"!proto/common/common_service.proto\x12\x1fcom.codio.chipmunk.proto.common\"\xc6\x01\n" +
	"\x18ForceUpdateConfigRequest\x12!\n" +
	"\fcodio_domain\x18\x01 \x01(\tR\vcodioDomain\x12\x1b\n" +
	"\tvm_domain\x18\x02 \x01(\tR\bvmDomain\x121\n" +
	"\x15no_vnc_client_version\x18\x03 \x01(\tR\x12noVncClientVersion\x12\x16\n" +
	"\x06branch\x18\x04 \x01(\tR\x06branch\x12\x1f\n" +
	"\vsign_secret\x18\x05 \x01(\tR\n" +
	"signSecret\"\x1b\n" +
	"\x19ForceUpdateConfigResponse\"\x1b\n" +
	"\x19GetChipmunkVersionRequest\"6\n" +
	"\x1aGetChipmunkVersionResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion2\xa5\x02\n" +
	"\x06Common\x12\x8a\x01\n" +
	"\x11ForceUpdateConfig\x129.com.codio.chipmunk.proto.common.ForceUpdateConfigRequest\x1a:.com.codio.chipmunk.proto.common.ForceUpdateConfigResponse\x12\x8d\x01\n" +
	"\x12GetChipmunkVersion\x12:.com.codio.chipmunk.proto.common.GetChipmunkVersionRequest\x1a;.com.codio.chipmunk.proto.common.GetChipmunkVersionResponseB6Z4github.com/codio/chipmunk-interface-gen/proto/commonb\x06proto3"

var (
	file_proto_common_common_service_proto_rawDescOnce sync.Once
	file_proto_common_common_service_proto_rawDescData []byte
)

func file_proto_common_common_service_proto_rawDescGZIP() []byte {
	file_proto_common_common_service_proto_rawDescOnce.Do(func() {
		file_proto_common_common_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_common_common_service_proto_rawDesc), len(file_proto_common_common_service_proto_rawDesc)))
	})
	return file_proto_common_common_service_proto_rawDescData
}

var file_proto_common_common_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_common_common_service_proto_goTypes = []any{
	(*ForceUpdateConfigRequest)(nil),   // 0: com.codio.chipmunk.proto.common.ForceUpdateConfigRequest
	(*ForceUpdateConfigResponse)(nil),  // 1: com.codio.chipmunk.proto.common.ForceUpdateConfigResponse
	(*GetChipmunkVersionRequest)(nil),  // 2: com.codio.chipmunk.proto.common.GetChipmunkVersionRequest
	(*GetChipmunkVersionResponse)(nil), // 3: com.codio.chipmunk.proto.common.GetChipmunkVersionResponse
}
var file_proto_common_common_service_proto_depIdxs = []int32{
	0, // 0: com.codio.chipmunk.proto.common.Common.ForceUpdateConfig:input_type -> com.codio.chipmunk.proto.common.ForceUpdateConfigRequest
	2, // 1: com.codio.chipmunk.proto.common.Common.GetChipmunkVersion:input_type -> com.codio.chipmunk.proto.common.GetChipmunkVersionRequest
	1, // 2: com.codio.chipmunk.proto.common.Common.ForceUpdateConfig:output_type -> com.codio.chipmunk.proto.common.ForceUpdateConfigResponse
	3, // 3: com.codio.chipmunk.proto.common.Common.GetChipmunkVersion:output_type -> com.codio.chipmunk.proto.common.GetChipmunkVersionResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_common_common_service_proto_init() }
func file_proto_common_common_service_proto_init() {
	if File_proto_common_common_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_common_common_service_proto_rawDesc), len(file_proto_common_common_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_common_common_service_proto_goTypes,
		DependencyIndexes: file_proto_common_common_service_proto_depIdxs,
		MessageInfos:      file_proto_common_common_service_proto_msgTypes,
	}.Build()
	File_proto_common_common_service_proto = out.File
	file_proto_common_common_service_proto_goTypes = nil
	file_proto_common_common_service_proto_depIdxs = nil
}
